### ISSUE TITLE
ERROR: This plugin is not a production of JetBrains. 

### ISSUE THREAD

**Issue by ycyin** [F4bioo/DiffLinesCounter#4]
Can not open my IDEA after install this plugin.
![image](https://github.com/F4bioo/DiffLinesCounter/assets/71380489/ebb7e924-91b3-45a6-9d7d-a5585d8e7d4c)

IDEA About Info：
IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023
Licensed to ***
Subscription is active until January 7, 2024.
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8

Kotlin: 231-1.8.21-IJ9011.34

**Comment by F4bioo** [comment]
Hi @yinyicao,

I'm really sorry for the inconvenience you're experiencing. I'm currently investigating what happened.

In the meantime, you can manually remove the plugin by navigating to the following path:

```
C:\Users\your-user\AppData\Roaming\JetBrains\IdeaIC2023...\plugins
```

Once you're in the plugins folder, please locate and delete the plugin folder associated with the issue. This should allow IntelliJ IDEA to start normally.

Thank you for your patience as we work to resolve this issue.

**Comment by F4bioo** [comment]
The issue has been resolved and the fix has been merged. A new version of the plugin will be released on the marketplace shortly. If you'd like to install the plugin manually in the meantime, it's available in the 'Release' section of the repository. Thank you for your patience and feedback. Closing this issue now.

Release
[v2.1.3](https://github.com/F4bioo/DiffLinesCounter/releases/tag/v2.1.3)
